#!/bin/bash

push=0
fetch=0

while [ ! $# -eq 0 ]
do
	case "$1" in
		--help | -h)
			echo "git remove-all-tags [-f | --fetch] [-p | --push] [-h | --help]"
			exit
			;;
		--push | -p)
			push=1
			;;
		--fetch | -f)
			fetch=1
			;;
	esac
	shift
done

if [ $fetch -eq 1 ]; then
	echo "fetching"
	git fetch
fi

tags=$(git tag -l)

if [ ${#tags} -eq 0 ]; then
	echo "no tags found"
	exit
fi

if [ $push -eq 1 ]; then
	echo "pushing delete"
	git push --delete origin $tags
fi

echo "local delete"
git tag -d $tags
exit
